Repository practicalProject8-A-5/Tiger-BE, pull requests merged in 2022-09, with the labels that each got.

#11 상품 이미지 등록/수정 및 회원가입/로그인 기능 관련 PR
  Tiger/build.gradle
  Tiger/src/main/java/com/tiger/TigerApplication.java
  Tiger/src/main/java/com/tiger/config/CorsConfig.java
  Tiger/src/main/java/com/tiger/config/SecurityConfig.java
  Tiger/src/main/java/com/tiger/config/WebConfig.java
  Tiger/src/main/java/com/tiger/config/security/jwt/JwtFilter.java
  Tiger/src/main/java/com/tiger/config/security/jwt/TokenProvider.java
  Tiger/src/main/java/com/tiger/controller/MemberController.java
  Tiger/src/main/java/com/tiger/controller/OAuthController.java
  Tiger/src/main/java/com/tiger/controller/VehicleController.java
  Tiger/src/main/java/com/tiger/domain/CommonResponseDto.java
  Tiger/src/main/java/com/tiger/domain/RefreshToken.java
  Tiger/src/main/java/com/tiger/domain/TokenDto.java
  Tiger/src/main/java/com/tiger/domain/UserDetailsImpl.java
  Tiger/src/main/java/com/tiger/domain/member/Member.java
  Tiger/src/main/java/com/tiger/domain/member/dto/EmailCheckRequestDto.java
  Tiger/src/main/java/com/tiger/domain/member/dto/KakaoUserInfoDto.java
  Tiger/src/main/java/com/tiger/domain/member/dto/LoginRequestDto.java
  Tiger/src/main/java/com/tiger/domain/member/dto/MemberRequestDto.java
  Tiger/src/main/java/com/tiger/domain/member/dto/RegisterRequestDto.java
  Tiger/src/main/java/com/tiger/domain/member/dto/ResponseDto.java
  Tiger/src/main/java/com/tiger/domain/vehicle/Vehicle.java
  Tiger/src/main/java/com/tiger/domain/vehicle/VehicleImage.java
  Tiger/src/main/java/com/tiger/domain/vehicle/dto/VehicleCommonResponseDto.java
  Tiger/src/main/java/com/tiger/domain/vehicle/dto/VehicleDetailResponseDto.java
  Tiger/src/main/java/com/tiger/domain/vehicle/dto/VehicleOwnerResponseDto.java
  Tiger/src/main/java/com/tiger/domain/vehicle/dto/VehicleRequestDto.java
  Tiger/src/main/java/com/tiger/exception/CustomException.java
  Tiger/src/main/java/com/tiger/exception/ErrorCode.java
  Tiger/src/main/java/com/tiger/exception/ErrorResponseEntity.java
  Tiger/src/main/java/com/tiger/exception/GlobalException.java
  Tiger/src/main/java/com/tiger/exception/StatusCode.java
  Tiger/src/main/java/com/tiger/repository/MemberRepository.java
  Tiger/src/main/java/com/tiger/repository/RefreshTokenRepository.java
  Tiger/src/main/java/com/tiger/repository/VehicleImageRepository.java
  Tiger/src/main/java/com/tiger/repository/VehicleRepository.java
  Tiger/src/main/java/com/tiger/service/AwsS3Service.java
  Tiger/src/main/java/com/tiger/service/MemberService.java
  Tiger/src/main/java/com/tiger/service/OAuthService.java
  Tiger/src/main/java/com/tiger/service/UserDetailsServiceImpl.java
  Tiger/src/main/java/com/tiger/service/VehicleService.java
  Tiger/src/main/resources/application.properties
  Tiger/src/main/resources/logback-spring.xml
  Tiger/src/test/java/com/tiger/utils/CheckUtilTest.java
Labels: enhancement

#16 refactor OpenDate
  Tiger/src/main/java/com/tiger/controller/OpenDateController.java
  Tiger/src/main/java/com/tiger/domain/openDate/OpenDate.java
  Tiger/src/main/java/com/tiger/exception/StatusCode.java
  Tiger/src/main/java/com/tiger/repository/OrderRepository.java
  Tiger/src/main/java/com/tiger/service/OpenDateService.java
  Tiger/src/main/java/com/tiger/service/OrderService.java
  Tiger/src/main/java/com/tiger/utils/CheckUtil.java
Labels: enhancement

#21 Vehicle 엔터티 수정 및 검색 쿼리 생성, HTTPS 연결
  Tiger/src/main/java/com/tiger/config/CorsConfig.java
  Tiger/src/main/java/com/tiger/config/SecurityConfig.java
  Tiger/src/main/java/com/tiger/config/security/jwt/JwtFilter.java
  Tiger/src/main/java/com/tiger/controller/MemberController.java
  Tiger/src/main/java/com/tiger/controller/OAuthController.java
  Tiger/src/main/java/com/tiger/controller/VehicleController.java
  Tiger/src/main/java/com/tiger/domain/vehicle/Vehicle.java
  Tiger/src/main/java/com/tiger/domain/vehicle/dto/VehicleCommonResponseDto.java
  Tiger/src/main/java/com/tiger/domain/vehicle/dto/VehicleCustomResponseDto.java
  Tiger/src/main/java/com/tiger/domain/vehicle/dto/VehicleDetailResponseDto.java
  Tiger/src/main/java/com/tiger/domain/vehicle/dto/VehicleOwnerResponseDto.java
  Tiger/src/main/java/com/tiger/domain/vehicle/dto/VehicleRequestDto.java
  Tiger/src/main/java/com/tiger/domain/vehicle/dto/VehicleSearch.java
  Tiger/src/main/java/com/tiger/domain/vehicle/dto/VehicleSearchResponseDto.java
  Tiger/src/main/java/com/tiger/repository/VehicleCustomRepository.java
  Tiger/src/main/java/com/tiger/service/MemberService.java
  Tiger/src/main/java/com/tiger/service/VehicleService.java
Labels: enhancement, productivity

#28 검색 쿼리 및 신규 차량 등록시 달력 에러 해결
  Tiger/src/main/java/com/tiger/repository/VehicleCustomRepository.java
  Tiger/src/main/java/com/tiger/service/OpenDateService.java
Labels: bug, enhancement

#29 기본 리팩터링 및 상품상세조회 및 검색조회 시 startDate과 endDate 따로 보내는 문제 해결
  Tiger/src/main/java/com/tiger/controller/MemberController.java
  Tiger/src/main/java/com/tiger/controller/OAuthController.java
  Tiger/src/main/java/com/tiger/controller/VehicleController.java
  Tiger/src/main/java/com/tiger/service/AwsS3Service.java
  Tiger/src/main/java/com/tiger/service/MemberService.java
  Tiger/src/main/java/com/tiger/service/OAuthService.java
  Tiger/src/main/java/com/tiger/service/VehicleService.java
  Tiger/src/main/java/com/tiger/utils/GenerateRandomUtil.java
  Tiger/src/main/java/com/tiger/utils/MapUtil.java
Labels: bug, enhancement

#32 <feat> openDateList 현재날짜기준으로 return하기
  Tiger/src/main/java/com/tiger/service/OpenDateService.java
Labels: bug

#44 WebSocket 구현 관련 PR
  Tiger/build.gradle
  Tiger/src/main/java/com/tiger/TigerApplication.java
  Tiger/src/main/java/com/tiger/config/CorsConfig.java
  Tiger/src/main/java/com/tiger/config/SecurityConfig.java
  Tiger/src/main/java/com/tiger/config/StompHandler.java
  Tiger/src/main/java/com/tiger/config/WebSocketConfig.java
  Tiger/src/main/java/com/tiger/config/security/jwt/JwtFilter.java
  Tiger/src/main/java/com/tiger/config/security/jwt/TokenProvider.java
  Tiger/src/main/java/com/tiger/controller/MemberController.java
  Tiger/src/main/java/com/tiger/controller/OAuthController.java
  Tiger/src/main/java/com/tiger/controller/VehicleController.java
  Tiger/src/main/java/com/tiger/domain/member/Member.java
  Tiger/src/main/java/com/tiger/exception/StatusCode.java
  Tiger/src/main/java/com/tiger/notification/EmitterRepository.java
  Tiger/src/main/java/com/tiger/notification/EmitterRepositoryImpl.java
  Tiger/src/main/java/com/tiger/notification/Notification.java
  Tiger/src/main/java/com/tiger/notification/NotificationController.java
  Tiger/src/main/java/com/tiger/notification/NotificationCountDto.java
  Tiger/src/main/java/com/tiger/notification/NotificationDto.java
  Tiger/src/main/java/com/tiger/notification/NotificationRepository.java
  Tiger/src/main/java/com/tiger/notification/NotificationRequestDto.java
  Tiger/src/main/java/com/tiger/notification/NotificationService.java
  Tiger/src/main/java/com/tiger/repository/MemberRepository.java
  Tiger/src/main/java/com/tiger/service/AwsS3Service.java
  Tiger/src/main/java/com/tiger/service/MemberService.java
  Tiger/src/main/java/com/tiger/service/OAuthService.java
  Tiger/src/main/java/com/tiger/service/VehicleService.java
  Tiger/src/main/java/com/tiger/websocket/ChatFilter.java
  Tiger/src/main/java/com/tiger/websocket/WebSocketController.java
  Tiger/src/main/java/com/tiger/websocket/chat/ChatMessage.java
  Tiger/src/main/java/com/tiger/websocket/chat/ChatMessageRepository.java
  Tiger/src/main/java/com/tiger/websocket/chat/ChatMessageService.java
  Tiger/src/main/java/com/tiger/websocket/chatDto/ChatUserRequestDto.java
  Tiger/src/main/java/com/tiger/websocket/chatDto/MessageRequestDto.java
  Tiger/src/main/java/com/tiger/websocket/chatDto/MessageResponseDto.java
  Tiger/src/main/java/com/tiger/websocket/chatDto/MessageTypeEnum.java
  Tiger/src/main/java/com/tiger/websocket/chatDto/RoomDto.java
  Tiger/src/main/java/com/tiger/websocket/chatDto/RoomMsgUpdateDto.java
  Tiger/src/main/java/com/tiger/websocket/chatDto/RoomResponseDto.java
  Tiger/src/main/java/com/tiger/websocket/chatDto/RoomStatusDto.java
  Tiger/src/main/java/com/tiger/websocket/chatroom/ChatRoom.java
  Tiger/src/main/java/com/tiger/websocket/chatroom/ChatRoomController.java
  Tiger/src/main/java/com/tiger/websocket/chatroom/ChatRoomRepository.java
  Tiger/src/main/java/com/tiger/websocket/chatroom/ChatRoomService.java
Labels: enhancement

#51 Vehicle 관련 변수명 리팩터링
  src/main/java/com/tiger/controller/VehicleController.java
  src/main/java/com/tiger/service/VehicleService.java
Labels: productivity

#56 검색 쿼리 개선 및 상품 이미지 수정 방식 개선
  src/main/java/com/tiger/config/security/jwt/TokenProvider.java
  src/main/java/com/tiger/controller/VehicleController.java
  src/main/java/com/tiger/domain/vehicle/Vehicle.java
  src/main/java/com/tiger/domain/vehicle/dto/VehicleDetailResponseDto.java
  src/main/java/com/tiger/domain/vehicle/dto/VehicleUpdateRequestDto.java
  src/main/java/com/tiger/repository/VehicleCustomRepository.java
  src/main/java/com/tiger/repository/VehicleImageRepository.java
  src/main/java/com/tiger/repository/VehicleRepository.java
  src/main/java/com/tiger/service/MemberService.java
  src/main/java/com/tiger/service/VehicleService.java
Labels: enhancement

#70 썸네일 이미지 수정 요청 처리 구현
  src/main/java/com/tiger/controller/VehicleController.java
  src/main/java/com/tiger/domain/vehicle/Vehicle.java
  src/main/java/com/tiger/domain/vehicle/dto/VehicleThumbnailRequestDto.java
  src/main/java/com/tiger/domain/vehicle/dto/VehicleThumbnailResponseDto.java
  src/main/java/com/tiger/exception/StatusCode.java
  src/main/java/com/tiger/notification/EmitterRepository.java
  src/main/java/com/tiger/notification/EmitterRepositoryImpl.java
  src/main/java/com/tiger/notification/NotificationController.java
  src/main/java/com/tiger/notification/NotificationCountDto.java
  src/main/java/com/tiger/notification/NotificationRequestDto.java
  src/main/java/com/tiger/notification/NotificationService.java
  src/main/java/com/tiger/service/VehicleService.java
Labels: enhancement

#72 메인 페이지 페이징 적용
  src/main/java/com/tiger/controller/VehicleController.java
  src/main/java/com/tiger/repository/VehicleRepository.java
  src/main/java/com/tiger/service/VehicleService.java
Labels: enhancement, productivity

#75 메인페이지 및 검색조회페이지 페이징 구현
  src/main/java/com/tiger/controller/VehicleController.java
  src/main/java/com/tiger/domain/vehicle/dto/VehicleUpdatePageResponseDto.java
  src/main/java/com/tiger/repository/VehicleCustomRepository.java
  src/main/java/com/tiger/service/VehicleService.java
Labels: enhancement

#82 회원가입, 로그인, 상품 등록, 상품 검색에서의 입력값 유효성 검사 추가
  src/main/java/com/tiger/controller/MemberController.java
  src/main/java/com/tiger/controller/VehicleController.java
  src/main/java/com/tiger/domain/member/dto/LoginRequestDto.java
  src/main/java/com/tiger/domain/member/dto/RegisterRequestDto.java
  src/main/java/com/tiger/domain/vehicle/Vehicle.java
  src/main/java/com/tiger/domain/vehicle/dto/VehicleRequestDto.java
  src/main/java/com/tiger/domain/vehicle/dto/VehicleSearch.java
  src/main/java/com/tiger/domain/vehicle/dto/VehicleUpdateRequestDto.java
Labels: enhancement

#86 S3 확장자 수정 (gfif 추가)
  src/main/java/com/tiger/service/AwsS3Service.java
Labels: enhancement

#87 XSS 방지
  build.gradle
  src/main/java/com/tiger/config/XssConfig.java
  src/main/java/com/tiger/exception/GlobalException.java
  src/main/java/com/tiger/exception/StatusCode.java
  src/main/java/com/tiger/secure/HTMLCharacterEscapes.java
  src/main/resources/lucy-xss-servlet-filter-rule.xml
  src/main/resources/web.xml
Labels: enhancement
